name: Test

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '*.yml'
      - '*.json'
      - '*.config'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  RYUJINX_BASE_VERSION: "1.1"
  
jobs:
  test:
    name: ${{ matrix.OS_NAME }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Debug, Release]
        include:
        - os: ubuntu-latest
          OS_NAME: Linux x64
          DOTNET_RUNTIME_IDENTIFIER: linux-x64

        - os: macOS-latest
          OS_NAME: macOS x64
          DOTNET_RUNTIME_IDENTIFIER: osx-x64

        - os: windows-latest
          OS_NAME: Windows x64
          DOTNET_RUNTIME_IDENTIFIER: win10-x64

      fail-fast: false
    steps:
      - uses: actions/checkout@v4
          
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          
      - name: Get git short hash
        id: git_short_hash
        run: echo "result=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Build
        run: |
         dotnet build -c "${{ matrix.configuration }}" -p:Version="${{ env.RYUJINX_BASE_VERSION }}" -p:SourceRevisionId="${{ steps.git_short_hash.outputs.result }}" -p:ExtraDefineConstants=DISABLE_UPDATER

      - name: Test
        run: |
         dotnet test --no-build -c "${{ matrix.configuration }}"
